name: 3DCellComposer
channels:
  - conda-forge
  - defaults
dependencies:
  - pip:
      - argparse
      - bz2file
      - cellsegmentationevaluator
      - deepcell
      - hubmap-ome-utils==0.3.4
      - numpy
      - pandas
      - pip==25.0.1
      - scikit-image
      - scipy
      - tensorflow==2.8.0
 